name: main
on:
  push:
    branches: [main]
  schedule:
  - cron: '55 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install git+https://github.com/aostrowski/pre-commit-mirror-maker@main
    - uses: fregante/setup-git-user@v1.1.0
    - run: pre-commit-mirror . --language=python --package-name=clang-format --id=git-clang-format --name='Check Git Diff with clang-format' --entry='git-clang-format -f' --types-or c++ --types-or c --types-or 'c#' --types-or cuda --types-or java --types-or javascript --types-or json --types-or objective-c --types-or proto --args=--style=file --require-serial
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/main --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
